<?php
namespace Garan24\Gateway\Aruispay;
use \Garan24\BaseConnector as BaseConnector;
use \Garan24\Gateway\Aruispay\Exception  as Garan24GatewayAruispayException;
use \Garan24\Interfaces\ITransaction as ITransaction;
class Sale extends BaseConnector implements ITransaction{
    /*******************************************************************************
     ** Sale Request Parameters
     * @param string[128]	client_orderid	- 	Merchant order identifier.
     * @param string[64k]	order_desc	- 	Brief order description
     * @param string[128]	card_printed_name	- 	Card printed name
     * @param string[50]	first_name	- 	Customer’s first name
     * @param string[50]	last_name	- 	Customer’s last name
     * @param int[4]|null	ssn	- 	Last four digits of the customer’s social security number.
     * @param int[8]|null	birthday	- 	Customer’s date of birth, in the format YYYYMMDD.
     * @param string[50]	address1	- 	Customer’s address line 1.
     * @param string[50]	city	- 	Customer’s city.
     * @param string[2]|null	state	- 	Customer’s state . Please see Reference for a list of valid state codes.
     * @param string[10]	zip_code	- 	Customer’s ZIP code
     * @param string[2]	country	- 	Customer’s country(two-letter country code). Please see Reference for a list of valid country codes.
     * @param string[15]	phone	- 	Customer’s full international phone number, including country code.
     * @param string[15]|null	cell_phone	- 	Customer’s full international cell phone number, including country code.
     * @param string[50]	email	- 	Customer’s email address.
     * @param int[10]	amount	- 	Amount to be charged. The amount has to be specified in the highest units with . delimiter. For instance, 10.5 for USD means 10 US Dollars and 50 Cents
     * @param string[3]	currency	- 	Currency the transaction is charged in (three-letter currency code). Sample values are: USD for US Dollar EUR for European Euro
     * @param int[20]	credit_card_number	- 	Customer’s credit card number.
     * @param int[2]	expire_month	- 	Credit card expiration month
     * @param int[4]	expire_year	- 	Credit card expiration year
     * @param int[3..4]	cvv2	- 	Customer’s CVV2 code. CVV2 (Card Verification Value) is a three- or four-digit number AFTER the credit card number in the signature area of the card.
     * @param string[20]	ipaddress	- 	Customer’s IP address, included for fraud screening purposes.
     * @param string[128]|null	site_url	- 	URL the original Sale is made from.
     * @param string[16..19]|null	destination-card-no	- 	Card number of destination card. for Money Send transactions
     * @param string[128]|null	purpose	- 	Destination to where the payment goes. It is useful for the merchants who let their clients to transfer money from a credit card to some type of client’s account, e.g. game or mobile phone account. Sample values are: +7123456789; gamer0001@ereality.com etc. This value will be used by fraud monitoring system.
     * @param string[40]	control	- 	Checksum generated by SHA-1. See Request authorization through control parameter for more details.
     * @param string[128]	redirect_url	- 	URL the cardholder will be redirected to upon completion of the transaction. Please note that the cardholder will be redirected in any case, no matter whether the transaction is approved or declined. You should not use this parameter to retrieve results from PaynetEasy gateway, because all parameters go through client’s browser and can be lost during transmission. To deliver the correct payment result to your backend use server_callback_url instead. Pass http://google.com if you use non3D schema for transactions processing and you have no need to return customer anywhere.
     * @param string[128]|null	server_callback_url	- 	URL the transaction result will be sent to. Merchant may use this URL for custom processing of the transaction completion, e.g. to collect sales data in Merchant’s database. See more details at Merchant Callbacks
     *******************************************************************************/
    protected $_request_data = [];
    protected $_response_data = [];
    protected $_method = "sale-form";
    public function __construct($data=[]){
        parent::__construct(["endpoint"=>"1145"]);
        $this->_request_data = $data;
    }
    /*******************************************************************************
     * Вызов метода REST.
     *
     * @param string $method вызываемый метод
     * @param array $data параметры вызова метода
     *
     * @return array
     ******************************************************************************/
    public function call(){
        $this->build();
        $this->_response_data = $this->query($this->_method,$this->_request_data);
        if(!isset($this->_response_data["type"])){
            throw new Garan24GatewayAruispayException("Error in response. Wrong format",500);
        }
        if(in_array($this->_response_data["type"],["async-form-response"])){
            throw new Garan24GatewayAruispayException(
                isset($this->_response_data["error-message"])?$this->_response_data["error-message"]:"Unknown message",
                isset($this->_response_data["error-code"])?$this->_response_data["error-code"]:500
            );
        }
        return true;
    }
    public function check(){
        $req = [
            "login" => $this->_merchant_login, //Merchant login name
            "client_orderid" => $this->_request_data["client_orderid"], //Merchant order identifier of the transaction for which the status is requested
            "orderid" => $this->_response_data["paynet-order-id"], //Order id assigned to the order by PaynetEasy
            "by-request-sn" => $this->_response_data["serial-number"], //Serial number assigned to the specific request by PaynetEasy. If this field exist in status request, status response return for this specific request.
            "control" => ""
        ];
        $req["control"] = $this->digest(
            $this->_merchant_login
            .$this->_request_data["client_orderid"]
            .$this->_response_data["paynet-order-id"]
            .$this->_merchant_key
        );
        $res = $this->query("status",$req);
        if(!isset($res["status"])){
            throw new Garan24GatewayAruispayException("Error in check order response. Wrong format",500);
        }
        if($res["status"]=="unknown"){
            throw new Garan24GatewayAruispayException("Error in check order response. Status = 'unknown'.",500);
        }
        if(in_array($res["status"], ["approved","declined","error","filtered"])) {
            $this->_response_data = array_merge($this->_response_data,$res);
            return true;
        }
        return false;
    }
    public function cancel(){
        $result = [];
        return $result;
    }
    protected function build(){
        $this->_request_data["merchant_control"] = $this->_merchant_key;
        $this->_request_data["control"] = $this->digest(
            trim($this->_endpoint)
            .trim($this->_request_data["client_orderid"])
            .preg_replace("/[\.,\-\s]/","",$this->_request_data["amount"])
            .trim($this->_request_data["email"])
            .trim($this->_request_data["merchant_control"])
        );
    }
    protected function digest($str){
        $str = preg_replace("/[\r\n\s]+/","",$str);
        $res = sha1($str);
        if($this->_debug){
            print("**********************************************************\n");
            print("SHA1\n{$str}\n{$res}\n");
            print("**********************************************************\n");
        }
        return $res;
    }
};
?>
